In [1]:
import sys
import numpy as np

range(10)

np.arange(1, 100, 12.21)

array([  1.  ,  13.21,  25.42,  37.63,  49.84,  62.05,  74.26,  86.47,
        98.68])

In [2]:
np.linspace(1, 3.14159, 20)

array([ 1.        ,  1.11271526,  1.22543053,  1.33814579,  1.45086105,
        1.56357632,  1.67629158,  1.78900684,  1.90172211,  2.01443737,
        2.12715263,  2.23986789,  2.35258316,  2.46529842,  2.57801368,
        2.69072895,  2.80344421,  2.91615947,  3.02887474,  3.14159   ])

In [3]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [4]:
[0]*10

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [7]:
np.zeros((10,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [9]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [10]:
np.ones(10)/3

array([ 0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333,
        0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333])

In [11]:
np.array([1,2,3,4,5,6])/14.0

array([ 0.07142857,  0.14285714,  0.21428571,  0.28571429,  0.35714286,
        0.42857143])

In [12]:
(np.array([1,2,3,4,5,6])/14.0)**3

array([ 0.00036443,  0.00291545,  0.00983965,  0.02332362,  0.04555394,
        0.0787172 ])

In [13]:
_**-3

array([  2.06610468e+10,   4.03536070e+07,   1.04968992e+06,
         7.88156387e+04,   1.05784560e+04,   2.05017563e+03])

In [14]:
2**np.array([1,2,3])

array([2, 4, 8])

In [18]:
a = np.array([1,2,3,4,5,6])

In [19]:
a.dtype

dtype('int32')

In [20]:
a = np.array([1,2,3,4,5,6.])
a.dtype

dtype('float64')

In [21]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [22]:
a*a

array([[ 1,  4],
       [ 9, 16]])

In [24]:
b=np.matrix([[1,2],[3,4]])
b

matrix([[1, 2],
        [3, 4]])

In [25]:
b*b

matrix([[ 7, 10],
        [15, 22]])

In [26]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [33]:
a = np.random.random(10)
a

array([ 0.99616979,  0.44752498,  0.12477095,  0.82855053,  0.09456587,
        0.82868465,  0.68248525,  0.61082955,  0.36179727,  0.96289687])

In [35]:
a.reshape(2,5)

array([[ 0.99616979,  0.44752498,  0.12477095,  0.82855053,  0.09456587],
       [ 0.82868465,  0.68248525,  0.61082955,  0.36179727,  0.96289687]])

In [39]:
A = np.matrix([[1,2],[3,4]])
b = np.array([5,5])
b*A

matrix([[20, 30]])

In [40]:
np.linalg.inv(A)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [41]:
np.linalg.eig(_)

(array([-2.68614066,  0.18614066]), matrix([[-0.82456484, -0.41597356],
         [ 0.56576746, -0.90937671]]))

In [44]:
np.linalg.cholesky(A*A.T)

matrix([[ 2.23606798,  0.        ],
        [ 4.91934955,  0.89442719]])

In [45]:
np.__config__.show()

lapack_opt_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd', 'mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd']
    library_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None)]
    include_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/include']
blas_opt_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', 'libifportmd']
    library_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/lib/intel64']
    define_macros = [('SCIPY_MKL_H', None)]
    include_dirs = ['C:/Program Files (x86)/Intel/Composer XE/mkl/include']
openblas_lapack_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_lapack95_lp64', 'mkl_blas95_lp64', 'mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'libiomp5md', '

In [47]:
data='''14 21431
3 1241
2 2334
1 43222'''
with open ('lesson_2_temp', 'w') as outfile:
    outfile.write(data)

In [51]:
tp = np.dtype([('time', 'float'), ('x', np.int32)])
T = np.loadtxt('lesson_2_temp', dtype=tp)

TypeError: data type "value" not understood